repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

# 1. Limpia los outputs de los Jupyter Notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        exclude: ^notebooks/(02_integracion_y_limpieza_datos|03_analisis_exploratorio)\.ipynb$

  # Formatea el código Python (incluso adentro de los notebooks)
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black-jupyter

  # Busca variables sin usar, imports de más y errores lógicos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]

# pre-commit run --all-files
